import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { ThemeModeScript } from "flowbite-react";
import { getTokenFromCookies } from "@/lib/auth/session";
import Sidebar from "@/components/ui/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Adatex",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const token = await getTokenFromCookies();
  if (!token) redirect("/login");
  return (
    <html lang="es" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Sidebar>{children}</Sidebar>
      </body>
    </html>
  );
}
