import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import Sidebar from "@/components/ui/Nav";
import { Toaster } from "react-hot-toast";
import { UserProvider } from "@/lib/contexts/UserContext";
import { SocketProvider } from "@/lib/contexts/SocketContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Adatex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" suppressHydrationWarning className="">
      <head></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SocketProvider>
          <UserProvider>
            <Sidebar>{children}</Sidebar>
            <Toaster
              position="top-right"
              toastOptions={{
                // Estilos para todos los toasts
                style: {
                  background: "#27272a", // zinc-800
                  color: "#fff",
                  border: "1px solid #3f3f46", // zinc-700
                },
                // Estilos específicos por tipo
                success: {
                  iconTheme: {
                    primary: "#10b981", // emerald-500
                    secondary: "#fff",
                  },
                },
                error: {
                  iconTheme: {
                    primary: "#ef4444", // red-500
                    secondary: "#fff",
                  },
                },
              }}
            />
          </UserProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
